trigger:
  # start a new build for every push
  batch: False
  branches:
    include:
      - 'main'
      - 'maint/*'
pr:
  branches:
    include:
      - '*'  # must quote since "*" is a YAML reserved character; we want a string

schedules:
- cron: "0 0 * * *"
  displayName: 'Daily midnight build'
  branches:
    include:
      - 'main'
      - 'maint/*'
  always: 'true'

stages:
- stage: Main
  jobs:
  - job: Pytest
    variables:
      DISPLAY: ':99'
    strategy:
      matrix:
        mne-dev:
          imageName: 'ubuntu-20.04'
          PYTHON_VERSION: '3.10'
          MNE: 'dev'
        mne-stable:
          imageName: 'ubuntu-20.04'
          PYTHON_VERSION: '3.10'
          MNE: 'stable'
    pool:
      vmImage: $(imageName)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(PYTHON_VERSION)
        architecture: 'x64'
        addToPath: true
    - bash: |
        set -e
        pip install -e .[full]
        pip install -e .[test]
      displayName: Install autoreject
    - script: pip install --upgrade https://github.com/mne-tools/mne-python/zipball/main
      displayName: Install MNE-Python dev version
      condition: eq(variables['MNE'], 'dev')
    - script: mne sys_info
      displayName: 'Print config'
    - script: python -m pytest . --cov=autoreject autoreject/tests/ --cov-report=xml --cov-config=setup.cfg --verbose
      displayName: Run pytest
    - bash: bash <(curl -s https://codecov.io/bash)
      displayName: 'Codecov'
      condition: succeededOrFailed()
