trigger:
  # start a new build for every push
  batch: False
  branches:
    include:
      - 'master'
      - 'maint/*'
pr:
  branches:
    include:
      - '*'  # must quote since "*" is a YAML reserved character; we want a string

schedules:
- cron: "0 0 * * *"
  displayName: 'Daily midnight build'
  branches:
    include:
      - 'master'
      - 'maint/*'
  always: 'true'

stages:
- stage: Main
  jobs:
  - job: Pytest
    variables:
      DISPLAY: ':99'
    strategy:
      matrix:
        mne-dev:
          imageName: 'ubuntu-20.04'
          PYTHON_VERSION: '3.10'
          MNE: 'dev'
        mne-stable:
          imageName: 'ubuntu-20.04'
          PYTHON_VERSION: '3.10'
          MNE: 'stable'
    pool:
      vmImage: $(imageName)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(PYTHON_VERSION)
        architecture: 'x64'
        addToPath: true
    - bash: |
        set -e
        pip install -e .[test]
      displayName: Install autoreject
    - script: git clone --depth 1 --single-branch --branch main https://github.com/mne-tools/mne-python.git -b main
      displayName: Clone MNE-Python
    - bash: source tools/get_testing_version.sh
      displayName: 'Get testing version'
      workingDirectory: mne-python
    - task: Cache@2
      inputs:
        key: $(testing_version)
        path: /home/vsts/mne_data
      displayName: 'Cache testing data'
    - script: python -c "import mne; mne.datasets.testing.data_path(verbose=True)"
      displayName: 'Get test data'
    - script: pip install -ve mne-python/
      displayName: Install MNE-Python dev version
      condition: eq(variables['MNE'], 'dev')
    - script: mne sys_info
      displayName: 'Print config'
    - script: pytest --cov=autoreject --cov-report=xml --cov-config=setup.cfg -v autoreject/
      displayName: Run pytest
    - bash: bash <(curl -s https://codecov.io/bash)
      displayName: 'Codecov'
      condition: succeededOrFailed()
